Readd yaml formatter

diff --git a/.github/actions/setup-environment/setup-k8s/action.yaml b/.github/actions/setup-environment/setup-k8s/action.yaml
--- a/.github/actions/setup-environment/setup-k8s/action.yaml
+++ b/.github/actions/setup-environment/setup-k8s/action.yaml
@@ -1,105 +1,101 @@
+---
 name: Setup Kubernetes
 description: Setup A kubernetes environment for charm qa
-
 inputs:
   environment:
-    description: "Environment to setup the k8s for"
-    required: True
+    description: Environment to setup the k8s for
+    required: true
   controller:
-    description: "Name of the controller to create"
-    required: True
+    description: Name of the controller to create
+    required: true
   model:
-    description: "Name of the model to create"
-    required: True
+    description: Name of the model to create
+    required: true
   kubeconfig_path:
-    description: "Path to kubeconfig file"
-    required: False
-    default: "/home/ubuntu/.kube/config"
+    description: Path to kubeconfig file
+    required: false
+    default: /home/ubuntu/.kube/config
 outputs:
   cloud-name:
-    description: "Name of the cloud created and bootstrapped to"
-    value:  ${{ steps.cloud.outputs.cloud }}
+    description: Name of the cloud created and bootstrapped to
+    value: ${{ steps.cloud.outputs.cloud }}
   kubeconfig_path:
-    description: "Path to kubeconfig file"
+    description: Path to kubeconfig file
     value: ${{ inputs.kubeconfig_path }}
-
 runs:
-  using: "composite"
+  using: composite
   steps:
-  - name: Setup Kubeconfig
-    env: 
-      environment: ${{ inputs.environment }}
-      kubeconfig_path: ${{ inputs.kubeconfig_path }}
-    shell: bash
-    run: |
-      mkdir -p $HOME/.kube
-      if [ "${environment}" = "production" ]; then
-        echo "${k8sprod}" > ${kubeconfig_path}
-      else        
-        echo "${k8sstg}" > ${kubeconfig_path}
-      fi
-  - name: Add K8s
-    env: 
-      environment: ${{ inputs.environment }}
-      kubeconfig_path: ${{ inputs.kubeconfig_path }}
-    shell: bash
-    id: cloud
-    run: |
-      export CLOUD="k8s-${environment}"
-      for ((attempt = 1; ; attempt++)); do
-        if KUBECONFIG="${kubeconfig_path}" juju add-k8s $CLOUD --client; then
-          break
-        elif [ "$attempt" -lt 3 ]; then
-          echo "Failed, retrying..."
-          sleep 5
-        else
-          exit 1
+    - name: Setup Kubeconfig
+      env:
+        environment: ${{ inputs.environment }}
+        kubeconfig_path: ${{ inputs.kubeconfig_path }}
+      shell: bash
+      run: |
+        mkdir -p $HOME/.kube
+        if [ "${environment}" = "production" ]; then
+          echo "${k8sprod}" > ${kubeconfig_path}
+        else        
+          echo "${k8sstg}" > ${kubeconfig_path}
         fi
-      done
-      echo "cloud=$CLOUD" >> $GITHUB_OUTPUT
-
-  - name: Set extra-options
-    shell: bash
-    id: extra-options
-    run: echo "extra-options=--bootstrap-constraints root-disk=5G" >> $GITHUB_OUTPUT
-
-  - name: Bootstrap Controller
-    env:
-      cloud: ${{ steps.cloud.outputs.cloud }}
-      controller: ${{ inputs.controller }}
-      extraoptions: ${{ steps.extra-options.outputs.extra-options }}
-    shell: bash
-    run: |
-      for ((attempt = 1; ; attempt++)); do
-        # Juju will prefix the namespace with "controller"
-        if juju bootstrap ${cloud} ${extraoptions} ${controller}; then
-          break
-        elif [ "$attempt" -lt 3 ]; then
-          echo "Failed, retrying..."
-          sleep 5
-        else
-          exit 1
-        fi
-      done
-
-  - name: Create Model
-    env:
-      model: ${{ inputs.model }}
-    shell: bash
-    run: |
-      for ((attempt = 1; ; attempt++))
-      do
-        if juju add-model ${model} \
-            --config "logging-config=DEBUG" \
-            --config="update-status-hook-interval=2m" \
-            --config="juju-http-proxy=http://squid.internal:3128" \
-            --config="juju-https-proxy=http://squid.internal:3128" \
-            --config="juju-no-proxy=127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com"; then
-          break
-        elif [ "$attempt" -lt 3 ]; then
-          echo "Failed, retrying..."
-          sleep 5
-        else
-          exit 1
-        fi
-      done
+    - name: Add K8s
+      env:
+        environment: ${{ inputs.environment }}
+        kubeconfig_path: ${{ inputs.kubeconfig_path }}
+      shell: bash
+      id: cloud
+      run: |
+        export CLOUD="k8s-${environment}"
+        for ((attempt = 1; ; attempt++)); do
+          if KUBECONFIG="${kubeconfig_path}" juju add-k8s $CLOUD --client; then
+            break
+          elif [ "$attempt" -lt 3 ]; then
+            echo "Failed, retrying..."
+            sleep 5
+          else
+            exit 1
+          fi
+        done
+        echo "cloud=$CLOUD" >> $GITHUB_OUTPUT
+    - name: Set extra-options
+      shell: bash
+      id: extra-options
+      run: echo "extra-options=--bootstrap-constraints root-disk=5G" >> $GITHUB_OUTPUT
+    - name: Bootstrap Controller
+      env:
+        cloud: ${{ steps.cloud.outputs.cloud }}
+        controller: ${{ inputs.controller }}
+        extraoptions: ${{ steps.extra-options.outputs.extra-options }}
+      shell: bash
+      run: |
+        for ((attempt = 1; ; attempt++)); do
+          # Juju will prefix the namespace with "controller"
+          if juju bootstrap ${cloud} ${extraoptions} ${controller}; then
+            break
+          elif [ "$attempt" -lt 3 ]; then
+            echo "Failed, retrying..."
+            sleep 5
+          else
+            exit 1
+          fi
+        done
+    - name: Create Model
+      env:
+        model: ${{ inputs.model }}
+      shell: bash
+      run: |-
+        for ((attempt = 1; ; attempt++))
+        do
+          if juju add-model ${model} \
+              --config "logging-config=DEBUG" \
+              --config="update-status-hook-interval=2m" \
+              --config="juju-http-proxy=http://squid.internal:3128" \
+              --config="juju-https-proxy=http://squid.internal:3128" \
+              --config="juju-no-proxy=127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com"; then
+            break
+          elif [ "$attempt" -lt 3 ]; then
+            echo "Failed, retrying..."
+            sleep 5
+          else
+            exit 1
+          fi
+        done
