[TS-132] Exit tests that provide invalid inputs to the bundle builder (#284)
* Handle bundle builder invalid inputs differently

* Add events for failure to setup substrate

diff --git a/.github/workflows/charm-testing.yaml b/.github/workflows/charm-testing.yaml
--- a/.github/workflows/charm-testing.yaml
+++ b/.github/workflows/charm-testing.yaml
@@ -229,8 +229,20 @@ jobs:
           controller: ${{ steps.juju_resources.outputs.controller }}
           model: ${{ steps.juju_resources.outputs.model }}
 
+      - name: Post 'setup_k8s_failed' event
+        if: ${{ failure() && env.test_observer_api != '' && inputs.execution_id != '' && steps.setup_k8s.conclusion == 'failure' }}
+        uses: ./.github/actions/test-observer/post-events
+        with:
+          test_observer_api: ${{ env.test_observer_api }}
+          test_observer_token: ${{ env.test_observer_token }}
+          test_execution_id: ${{ inputs.execution_id }}
+          job_uuid: ${{ inputs.environment }}/${{ inputs.execution_id }}
+          event_name: "setup_k8s_failed"
+          detail: "Setup of Kubernetes cloud failed."
+
       - name: Setup O7k Cloud
         if: ${{ inputs.substrate == 'openstack'}}
+        id: setup_o7k
         uses: ./.github/actions/setup-environment/setup-openstack
         env:
           o7kprod: ${{ secrets.PROD_SQA_NOVARC }}
@@ -239,6 +251,17 @@ jobs:
           environment: ${{ inputs.environment }}
           controller: ${{ steps.juju_resources.outputs.controller }}
           model: ${{ steps.juju_resources.outputs.model }}
+
+      - name: Post 'setup_o7k_failed' event
+        if: ${{ failure() && env.test_observer_api != '' && inputs.execution_id != '' && steps.setup_o7k.conclusion == 'failure' }}
+        uses: ./.github/actions/test-observer/post-events
+        with:
+          test_observer_api: ${{ env.test_observer_api }}
+          test_observer_token: ${{ env.test_observer_token }}
+          test_execution_id: ${{ inputs.execution_id }}
+          job_uuid: ${{ inputs.environment }}/${{ inputs.execution_id }}
+          event_name: "setup_o7k_failed"
+          detail: "Setup of OpenStack cloud failed."
 
       - name: Debug Setup
         if: ${{ !cancelled() && inputs.debug_sleep_after == 'setup' }}
@@ -285,24 +308,61 @@ jobs:
           set -e
 
           # Handle the result
-          if [ "$rc" -eq 2 ]; then
-            echo "Bundle generation failed due to invalid input" >&2
-          elif [ "$rc" -ne 0 ]; then
-            echo "Bundle generation failed (exit code $rc)" >&2
-            exit $rc
-          else
-            echo "bundle=$(realpath generated-bundle.yaml)" >> $GITHUB_OUTPUT
-
-            echo '### Generated Bundle Mermaid Diagram' >> $GITHUB_STEP_SUMMARY
-            echo '```mermaid' >> $GITHUB_STEP_SUMMARY
-            cat generated-bundle.mmd >> $GITHUB_STEP_SUMMARY
-            echo '```' >> $GITHUB_STEP_SUMMARY
-
-            echo '### Generated Juju Bundle' >> $GITHUB_STEP_SUMMARY
-            echo '```yaml' >> $GITHUB_STEP_SUMMARY
-            cat generated-bundle.yaml >> $GITHUB_STEP_SUMMARY
-            echo '```' >> $GITHUB_STEP_SUMMARY
+          if [ "$rc" -ne 0 ]; then
+            if [ "$rc" -eq 2 ]; then
+              echo "Bundle generation failed due to invalid input" >&2
+              echo "invalid_input=true" >> $GITHUB_OUTPUT
+            else
+              echo "Bundle generation failed (exit code $rc)" >&2
+            fi
+            exit "$rc"
           fi
+
+          # Note the generated bundles
+          echo "bundle=$(realpath generated-bundle.yaml)" >> $GITHUB_OUTPUT
+
+          echo '### Generated Bundle Mermaid Diagram' >> $GITHUB_STEP_SUMMARY
+          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
+          cat generated-bundle.mmd >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+          echo '### Generated Juju Bundle' >> $GITHUB_STEP_SUMMARY
+          echo '```yaml' >> $GITHUB_STEP_SUMMARY
+          cat generated-bundle.yaml >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+      - name: Post 'bundle_generated' event
+        if: ${{ env.test_observer_api != '' && inputs.execution_id != '' }}
+        uses: ./.github/actions/test-observer/post-events
+        with:
+          test_observer_api: ${{ env.test_observer_api }}
+          test_observer_token: ${{ env.test_observer_token }}
+          test_execution_id: ${{ inputs.execution_id }}
+          job_uuid: ${{ inputs.environment }}/${{ inputs.execution_id }}
+          event_name: "bundle_generated"
+          detail: "Bundle generated."
+
+      - name: Post 'bundle_generation_failed' event
+        if: ${{ failure() && env.test_observer_api != '' && inputs.execution_id != '' && steps.build_bundle.conclusion == 'failure' && steps.build_bundle.outputs.invalid_input != 'true' }}
+        uses: ./.github/actions/test-observer/post-events
+        with:
+          test_observer_api: ${{ env.test_observer_api }}
+          test_observer_token: ${{ env.test_observer_token }}
+          test_execution_id: ${{ inputs.execution_id }}
+          job_uuid: ${{ inputs.environment }}/${{ inputs.execution_id }}
+          event_name: "bundle_generation_failed"
+          detail: "Bundle generation failed."
+
+      - name: Post 'bundle_generation_invalid_input' event
+        if: ${{ failure() && env.test_observer_api != '' && inputs.execution_id != '' && steps.build_bundle.conclusion == 'failure' && steps.build_bundle.outputs.invalid_input == 'true' }}
+        uses: ./.github/actions/test-observer/post-events
+        with:
+          test_observer_api: ${{ env.test_observer_api }}
+          test_observer_token: ${{ env.test_observer_token }}
+          test_execution_id: ${{ inputs.execution_id }}
+          job_uuid: ${{ inputs.environment }}/${{ inputs.execution_id }}
+          event_name: "bundle_generation_invalid_input"
+          detail: "Bundle generation failed due to invalid input."
 
       - name: Post 'test_deploy_start' event
         if: ${{ env.test_observer_api != '' && inputs.execution_id != '' }}
@@ -608,7 +668,7 @@ jobs:
           status: ${{ steps.calculate_job_status.outputs.test_status != '' && steps.calculate_job_status.outputs.test_status || 'ENDED_PREMATURELY' }}
 
       - name: Trigger rerun on Test Observer if failure
-        if: ${{ failure() && env.test_observer_api != '' && inputs.execution_id != '' }}
+        if: ${{ failure() && env.test_observer_api != '' && inputs.execution_id != '' && !(steps.build_bundle.conclusion == 'failure' && steps.build_bundle.outputs.invalid_input == 'true') }}
         uses: ./.github/actions/test-observer/trigger-rerun
         with:
           test_observer_api: ${{ env.test_observer_api }}
